### ISSUE TITLE
how to trigger 404 page in different subfolders

### ISSUE THREAD

**Issue by sbwww** [shu1007/slidev-gh-page-template#1]
I'd like to deploy the slide in a subfolder of a repo (the repo contains multiple subfolders, each subfolder holds a slide).

e.g., I have 2 subfolders `xxx.github.io/Slides/slideA` and `xxx.github.io/Slides/slideB`, each containing an `index.html` and a `404.html`.

However, when I refresh the page `xxx.github.io/Slides/slideA/1`, the 404 page in the repo root is triggered. What should I do to trigger the 404 page in the subfolder `slideA`?

I'm not familiar with frontend issues. It will be a great help if you would give me some straightforward instructions. Thank you in advance!

**Comment by shu1007** [comment]
This is based on the following link.

https://dev.to/_evansalter/github-pages-and-single-page-apps

In order for this to work, need the script to work in index.html in the root above the subdirectory.
